// Mock Data - Geliştirme aşaması için
// Supabase kurulduktan sonra bu veriler veritabanından gelecek

import { Category, Product, News, Slider } from '@/types/database'

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Suntalem Sofralar',
    slug: 'yer-sofralari',
    description: 'Geleneksel kullanım için üretilen melamin kaplı yer sofraları',
    image_url: '/images/categories/sofralar.jpg',
    order: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '2',
    name: 'Suntalem Masalar',
    slug: 'masalar',
    description: 'Yemek ve çalışma masaları',
    image_url: '/images/categories/masalar.jpg',
    order: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '3',
    name: 'Plastik Ürünler',
    slug: 'plastik',
    description: 'Dayanıklı plastik ev gereçleri ve endüstriyel parçalar',
    image_url: '/images/categories/plastik.jpg',
    order: 3,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '4',
    name: 'Metal Ürünler',
    slug: 'metal',
    description: 'Paslanmaz krom metal ürünler',
    image_url: '/images/categories/metal.jpg',
    order: 4,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '5',
    name: 'Ahşap Ürünler',
    slug: 'ahsap',
    description: 'Doğal ahşap ev gereçleri',
    image_url: '/images/categories/ahsap.jpg',
    order: 5,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '6',
    name: 'Hırdavat',
    slug: 'hirdavat',
    description: 'Dübel ve bağlantı elemanları',
    image_url: '/images/categories/hirdavat.jpg',
    order: 6,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
]

export const mockProducts: Product[] = [
  // Suntalem Sofralar
  {
    id: '1',
    name: 'Sivas Sofrası',
    slug: 'sivas-sofrasi',
    description: 'Geleneksel Sivas tasarımlı yer sofrası. 18mm melamin kaplı yonga levha.',
    short_description: 'Geleneksel tasarım, dayanıklı yapı',
    category_id: '1',
    material: 'suntalem',
    features: [],
    dimensions: { diameter: 80, unit: 'cm' },
    images: ['/images/products/sivas-sofrasi.jpg'],
    is_featured: true,
    is_popular: true,
    is_active: true,
    order: 1,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '2',
    name: 'Yer Sofrası',
    slug: 'yer-sofrasi',
    description: 'Farklı çap seçenekleriyle yer sofrası.',
    short_description: '60cm ve 70cm seçenekleri',
    category_id: '1',
    material: 'suntalem',
    variants: [
      { id: 'v1', name: '60 cm' },
      { id: 'v2', name: '70 cm' },
    ],
    images: ['/images/products/yer-sofrasi.jpg'],
    is_featured: false,
    is_popular: true,
    is_active: true,
    order: 2,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '3',
    name: 'Mutfak Yardımcı Sofrası',
    slug: 'mutfak-yardimci-sofrasi',
    description: 'Kompakt boyutlu, mutfak kullanımı için ideal.',
    short_description: 'Kompakt ve kullanışlı',
    category_id: '1',
    material: 'suntalem',
    images: ['/images/products/mutfak-sofrasi.jpg'],
    is_featured: false,
    is_popular: false,
    is_active: true,
    order: 3,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  // Suntalem Masalar
  {
    id: '4',
    name: 'Katlanır Masa',
    slug: 'katlanir-masa',
    description: 'Yer kaplamayan, mekanizmalı katlanır masa.',
    short_description: 'Katlanır, pratik kullanım',
    category_id: '2',
    material: 'suntalem',
    features: ['katlanir'],
    images: ['/images/products/katlanir-masa.jpg'],
    is_featured: true,
    is_popular: true,
    is_active: true,
    order: 1,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '5',
    name: 'Ayaklı Masa',
    slug: 'ayakli-masa',
    description: 'Standart dört ayaklı yemek masası.',
    short_description: 'Klasik tasarım',
    category_id: '2',
    material: 'suntalem',
    images: ['/images/products/ayakli-masa.jpg'],
    is_featured: false,
    is_popular: false,
    is_active: true,
    order: 2,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '6',
    name: 'Fiskos (Yan Sehpa)',
    slug: 'fiskos-sehpa',
    description: 'Üç ayaklı yuvarlak yan sehpa.',
    short_description: 'Şık yan sehpa',
    category_id: '2',
    material: 'suntalem',
    images: ['/images/products/fiskos.jpg'],
    is_featured: false,
    is_popular: false,
    is_active: true,
    order: 3,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  // Plastik Ürünler
  {
    id: '7',
    name: 'Katlanır Tabure',
    slug: 'katlanir-tabure',
    description: 'ABC desenli katlanır plastik tabure.',
    short_description: 'Katlanır, renkli seçenekler',
    category_id: '3',
    material: 'plastik',
    features: ['katlanir'],
    images: ['/images/products/katlanir-tabure.jpg'],
    is_featured: true,
    is_popular: true,
    is_active: true,
    order: 1,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '8',
    name: 'Banyo Taburesi',
    slug: 'banyo-taburesi',
    description: 'Islak zemin için uygun banyo taburesi.',
    short_description: 'Islak zemine dayanıklı',
    category_id: '3',
    material: 'plastik',
    features: ['islak_zemin'],
    images: ['/images/products/banyo-taburesi.jpg'],
    is_featured: false,
    is_popular: false,
    is_active: true,
    order: 2,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '9',
    name: 'Geçmeli Roket Tabure',
    slug: 'gecmeli-roket-tabure',
    description: 'İstiflenebilir tasarım, lojistik avantajı.',
    short_description: 'İstiflenebilir',
    category_id: '3',
    material: 'plastik',
    features: ['gecmeli'],
    images: ['/images/products/roket-tabure.jpg'],
    is_featured: false,
    is_popular: false,
    is_active: true,
    order: 3,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '10',
    name: 'Renkli Maşrapa',
    slug: 'renkli-masrapa',
    description: 'Geleneksel banyo tası, çeşitli renk seçenekleri.',
    short_description: 'Çeşitli renkler',
    category_id: '3',
    material: 'plastik',
    variants: [
      { id: 'v1', name: 'Kırmızı' },
      { id: 'v2', name: 'Mavi' },
      { id: 'v3', name: 'Yeşil' },
      { id: 'v4', name: 'Beyaz' },
    ],
    images: ['/images/products/masrapa.jpg'],
    is_featured: false,
    is_popular: true,
    is_active: true,
    order: 4,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '11',
    name: 'Mangal Yelpazesi',
    slug: 'mangal-yelpazesi',
    description: 'Piknik ve mangal için plastik yelpaze.',
    short_description: 'Piknik aksesuarı',
    category_id: '3',
    material: 'plastik',
    images: ['/images/products/mangal-yelpazesi.jpg'],
    is_featured: false,
    is_popular: false,
    is_active: true,
    order: 5,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  // Metal Ürünler
  {
    id: '12',
    name: 'Krom Ayakkabılık',
    slug: 'krom-ayakkabiik',
    description: 'Paslanmaz renkli krom ayakkabılık. Dayanıklı ve estetik.',
    short_description: 'Paslanmaz krom',
    category_id: '4',
    material: 'metal',
    features: ['paslanmaz'],
    images: ['/images/products/krom-ayakkabiik.jpg'],
    is_featured: true,
    is_popular: true,
    is_active: true,
    order: 1,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '13',
    name: 'Katlanır Kurutmalık',
    slug: 'katlanir-kurutmalik',
    description: 'Katlanabilir çamaşır kurutmalık.',
    short_description: 'Katlanır tasarım',
    category_id: '4',
    material: 'metal',
    features: ['katlanir'],
    images: ['/images/products/kurutmalik.jpg'],
    is_featured: false,
    is_popular: false,
    is_active: true,
    order: 2,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '14',
    name: 'Demonte Antik Portmanto',
    slug: 'demonte-antik-portmanto',
    description: 'Sökme takmalı antik görünümlü portmanto. Kolay kurulum, kaliteli malzeme.',
    short_description: 'Demonte, antik tasarım',
    category_id: '4',
    material: 'metal',
    features: ['demonte'],
    images: ['/images/products/portmanto.jpg'],
    is_featured: true,
    is_popular: true,
    is_active: true,
    order: 3,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  // Ahşap Ürünler
  {
    id: '15',
    name: 'Ahşap Ayakkabılık',
    slug: 'ahsap-ayakkabiik',
    description: 'Doğal ahşap ayakkabılık.',
    short_description: 'Doğal ahşap',
    category_id: '5',
    material: 'ahsap',
    images: ['/images/products/ahsap-ayakkabiik.jpg'],
    is_featured: false,
    is_popular: false,
    is_active: true,
    order: 1,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '16',
    name: 'Demlik Altlık',
    slug: 'demlik-altlik',
    description: 'Ahşap demlik/çaydanlık altlığı.',
    short_description: 'Mutfak aksesuarı',
    category_id: '5',
    material: 'ahsap',
    images: ['/images/products/demlik-altlik.jpg'],
    is_featured: false,
    is_popular: false,
    is_active: true,
    order: 2,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  // Hırdavat
  {
    id: '17',
    name: 'Fombort Dübeli',
    slug: 'fombort-dubeli',
    description: 'Her ölçüde üretilen yüksek kaliteli fombort dübeli.',
    short_description: 'Çeşitli ölçüler',
    category_id: '6',
    variants: [
      { id: 'v1', name: '6mm' },
      { id: 'v2', name: '8mm' },
      { id: 'v3', name: '10mm' },
    ],
    images: ['/images/products/dubel.jpg'],
    is_featured: false,
    is_popular: true,
    is_active: true,
    order: 1,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '18',
    name: 'Metal Sofra Ayağı',
    slug: 'metal-sofra-ayagi',
    description: 'Suntalem sofralar için yedek metal ayak.',
    short_description: 'Yedek parça',
    category_id: '6',
    material: 'metal',
    variants: [
      { id: 'v1', name: '1 Numara' },
      { id: 'v2', name: '2 Numara' },
      { id: 'v3', name: '3 Numara' },
      { id: 'v4', name: '4 Numara' },
    ],
    images: ['/images/products/sofra-ayagi.jpg'],
    is_featured: false,
    is_popular: false,
    is_active: true,
    order: 2,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
]

export const mockNews: News[] = [
  {
    id: '1',
    title: 'Yeni Sezon Ürünlerimiz',
    slug: 'yeni-sezon-urunlerimiz',
    content: 'Üç Yıldız Metal olarak 2024 sezonunda yeni ürün gamımızla sizlerleyiz. Modern tasarımlar ve yüksek kalite standartlarımızla üretimimize devam ediyoruz.',
    excerpt: '2024 sezonunda yeni ürün gamımızla sizlerleyiz.',
    image_url: '/images/news/yeni-sezon.jpg',
    is_published: true,
    published_at: '2024-01-15',
    view_count: 1250,
    created_at: '2024-01-15',
    updated_at: '2024-01-15'
  },
  {
    id: '2',
    title: 'Fabrika Kapasite Artışı',
    slug: 'fabrika-kapasite-artisi',
    content: 'Sivas Organize Sanayi Bölgesindeki tesisimizde kapasite artırım çalışmalarımız tamamlanmıştır. Yeni üretim hatlarımızla daha hızlı ve kaliteli üretim yapabilmekteyiz.',
    excerpt: 'Kapasite artırım çalışmalarımız tamamlandı.',
    image_url: '/images/news/fabrika.jpg',
    is_published: true,
    published_at: '2024-02-01',
    view_count: 890,
    created_at: '2024-02-01',
    updated_at: '2024-02-01'
  },
]

export const mockSliders: Slider[] = [
  {
    id: '1',
    title: "Sivas'tan Dünyaya",
    subtitle: 'Kaliteli Üretim',
    description: '25+ yıllık tecrübe ile metal, plastik ve ahşap ev gereçleri üretiyoruz.',
    image_url: '/images/slider/slider-1.jpg',
    button_text: 'Ürünlerimizi Keşfedin',
    button_link: '/urunler',
    order: 1,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '2',
    title: '15.000 m² Üretim Tesisi',
    subtitle: 'Modern Altyapı',
    description: 'Sivas Organize Sanayi Bölgesinde 4.000 m² kapalı üretim alanı.',
    image_url: '/images/slider/slider-2.jpg',
    button_text: 'Fabrikamızı İnceleyin',
    button_link: '/kurumsal',
    order: 2,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
  {
    id: '3',
    title: 'Toptan Satış',
    subtitle: 'B2B Çözümler',
    description: 'Bayilerimize ve kurumsal müşterilerimize özel fiyatlandırma.',
    image_url: '/images/slider/slider-3.jpg',
    button_text: 'Teklif Alın',
    button_link: '/teklif',
    order: 3,
    is_active: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01'
  },
]
